# Generated by Django 4.2.9 on 2024-01-30 00:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Directeur', 'Directeur'), ('Gestionnaire', 'Gestionnaire'), ('Conseiller', 'Conseiller'), ('Utilisateur', 'Utilisateur')], default='Utilisateur', max_length=50, null=True),
        ),
    ]
